apiVersion: apps/v1
kind: Deployment
metadata:
  name: student-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: student-app
  template:
    metadata:
      labels:
        app: student-app
    spec:
      containers:
      - name: student-app
        image: zainebheni/student-management:latest
        ports:
        - containerPort: 8089
        # volumeMounts optionnel pour logs
        # volumeMounts:
        # - name: student-app-logs
        #   mountPath: /opt/student-app/logs
      # volumes optionnel pour logs
      # volumes:
      # - name: student-app-logs
      #   emptyDir: {}
