apiVersion: v1
kind: Service
metadata:
  name: student-app-service
spec:
  type: NodePort
  selector:
    app: student-app
  ports:
  - port: 8080           # port exposé dans le cluster
    targetPort: 8080     # correspond au containerPort
    nodePort: 30081      # port externe pour accéder à l'application depuis l'extérieur

