pipeline {
    agent any

    tools {
        jdk 'JDK17'        
        maven 'Maven363'   
    }

    stages {
        stage('Start') {
            steps {
                echo 'Début du pipeline Jenkins - Premier test'
            }
        }

        stage('Check Tools') {
            steps {
                sh 'java -version'
                sh 'mvn -version'
                sh 'git --version'
            }
        }

        stage('Build') {
            steps {
                echo ' Compilation du projet'
                sh 'mvn clean compile'
            }
        }

        stage('Test') {
            steps {
                echo 'Exécution des tests'
                sh 'mvn test'
            }
        }
    }

    post {
        always {
            echo ' Pipeline terminé'
        }
    }
}
